name: CI Pipeline for test-aja branch

on:
  push:
    branches:
      - test-aja

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: python src/train_model.py

      - name: Commit and push model files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add models/
          git commit -m "Add trained model files [skip ci]" || echo "No changes to commit"
          git push origin test-aja
